### ISSUE TITLE
Setup basic GitHub pages workflow for website deployment

### ISSUE THREAD

**Issue by LarsEck** [KairosResearchLab/Kairos#113]

**Comment by sebescudie** [comment]
Cross-referencing #110 and #115 here. The workflow I've been using is basically that :

- Create a repo for your website (`blabla.github.io`)
- Pull it, create a Hugo project from `cmd`
- Add the repo of the theme you wanna use as a submodule
- Customize it as you like locally, create content
- Setup a Github workflow that builds the website and pushes it another branch that will be used when one tries to access the website from their browser. This workflow should trigger on push to `main`
- Push to main, the website will be automagically deployed.

**Comment by LarsEck** [comment]
Very nice! I'm personally tending towards using https://astro.build for all of this and the workflow is essentially the same as you described for Hugo. Astro has a [nice page in their docs](https://docs.astro.build/en/guides/deploy/github/) covering deployment to GitHub Pages. They have a predefined action for this which can be found [here](https://github.com/withastro/action).
