### ISSUE TITLE
Rename IBackgroundFunction

### ISSUE THREAD

**Issue by natan-sinigaglia** [KairosResearchLab/Kairos#189]

**Comment by gregsn** [comment]
`IBackground` or just `Background`?
`BackgroundProvider`?

**Comment by natan-sinigaglia** [comment]
BackgroundProvider sounds correct to me
(Just background would be misleading, since this thing is something that you can ask for a background, it's not the background itself)

**Comment by natan-sinigaglia** [comment]
I would go for IBackgroundProvider
I like having "I" at the beginning when is about interfaces. it hints you to the fact that it's not a specific class but it's a category of objects.
what you think? @gregsn
