### ISSUE TITLE
Throw warning if as service is not found

### ISSUE THREAD

**Issue by sebescudie** [KairosResearchLab/Kairos#199]
So we'll hide the `Found` pin (see #198), but we can still make use of it internally to throw a warning if a service is not found.

**Comment by natan-sinigaglia** [comment]
@gregsn @azeno  do you think is possible to have clear feedback when the adaptive mechanism can't find any matching?
instead of throwing exception there could be a text in the log and an orange node

**Comment by azeno** [comment]
Yesterday night I thought about adding a fallback implementation. It basically needs to take the most general form matching if nothing else matches. That fallback implementation could then take care of displaying messages etc.
