### ISSUE TITLE
Imgui prototyping issues

### ISSUE THREAD

**Issue by natan-sinigaglia** [KairosResearchLab/Kairos#213]
Issues or misunderstandings of imgui library found during development of timeline UI:

- Docking:
 - doesn't work properly in main renderer window. Only works inside window widgets (Tri SetNextWindowFullscreen)
 - we would need to create a window that always fit with the render window
 - docking layout doesn't update when you rescale the render window
- Layout:
 - we need widgets like StackX and StackY (Try Table region)
 - Grid layout (Try Table region)
- Windows
 - Not clear how the retrieve the Context of a window/widget  (eg. wanting to get bounds to draw something on top of a window)  (Anton is taking a look to this)
 - no way to create a window??? there's a way to destroy them tho!
- Popup menu not moveable/resizeable after creation (Anton is taking a look to this)

**Comment by antongit** [comment]
@lasalillo It looks like `GetItemRectMin`, `GetItemRectMax` working properly.
Check this. Please check other nodes from the Queries category, they window is treated as a widget as well and there are queries that can be placed into the window region and other (like these `GetItem...`) afterwords.

![image](https://user-images.githubusercontent.com/1189037/203275139-a497ebb2-da88-4681-be8c-55c6fe9d0f58.png)

[ItemBounds.zip](https://github.com/KairosResearchLab/Kairos/files/10065902/ItemBounds.zip)

**Comment by antongit** [comment]
@natan-sinigaglia:
"Not clear how the retrieve the Context of a window/widget (eg. wanting to get bounds to draw something on top of a window) (Anton is taking a look to this)"

Not sure what do you mean by the context in this regard. Maybe my answer above answers it already? For windows in particular, you can use `GetWindowSize` (as an example) inside of the window, to get its size, or other queries like `GetContentRegionAvail`.

**Comment by lasalillo** [comment]
@antongit I think the problem was that i was considering also the Windows as Item. 
Using  GetItemRectMin, GetItemRectMax for normal Widgets looks consistent.
Thanks

**Comment by antongit** [comment]
@lasalillo Yes, probably the proper helptext is missing for the GetItemRect... nodes. Will try to find something about it the ImGui: what they treat as an "Item" in this case and what not.

**Comment by lasalillo** [comment]
@antongit Thank you.

Also, regarding Docking: 
Still not having good results with it. 
The main problem is that it only works in a understandable way inside a Window (with different dimensions than the canvas), as soon as the Window has the same size than the Renderer screen (using SetNextWindowFullscreen or defining the Rectangle with the ClientBounds from Renderer), the docking mechanism doesn't work as spected, in other words, it's like not having any window and Docking directly to the screen.  

Hard to explain, easy to see.

Maybe i'm missing something here, it would be great if you can provide an example we can use.

**Comment by antongit** [comment]
@lasalillo Re: Opening and closing windows.
ImGui treats windows a bit differently than say `CollapsingHeader` that also can be collapsed or closed (not visible).
In the upcoming preview (2022.5) you'll be able to close the window like this:

![image](https://user-images.githubusercontent.com/1189037/203436895-c3a3a224-78f7-415c-a3ed-7ce6733c2b9e.png)

[HowTo Open And Close a Window.zip](https://github.com/KairosResearchLab/Kairos/files/10071641/HowTo.Open.And.Close.a.Window.zip)

This is how original ImGui defines this:
https://github.com/ocornut/imgui/blob/5bb287494096461f90eb5d18135f7c4809efd2f5/imgui.h#L318

Probably @gregsn or @azeno will review this later.

**Comment by antongit** [comment]
@lasalillo Re: Popups/Modals:
Probably the Bounds pin should be removed, then the Popup/Modal will be draggable and if one wants to set it to a particular place, the `SetNextWindowPos/Size` nodes can be used.
See: https://github.com/vvvv/VL.ImGui/issues/51

It looks like ImGui doesn't provide Resize Handle for the Popup/Modal Windows.
Can't find anything about it in the DemoWindow and in the Enums.

**Comment by natan-sinigaglia** [comment]
hey @antongit  thanks for the help here!
sorry I just saw the messages, it's more air that is taking care of this part ;)
