### ISSUE TITLE
UI Timeline Drag N' Drop a Keyframe -> Keyframe got lost above 1 or below 0

### ISSUE THREAD

**Issue by CeeYaa** [KairosResearchLab/Kairos#249]
It happend that I accidentally drag Keyframes above the topY (so value: 1) and dropped it there. For example value: (value:1.5) 
The problem now is: I cannot select this keyframe anymore or scale the Value-Range  

![image](https://user-images.githubusercontent.com/1171084/212489678-677a82e2-5a76-4c40-a5bd-0ed1e8677394.png)

**Comment by natan-sinigaglia** [comment]
I just changed the mapping to clamp.
wait for the next nuget ;)
