### ISSUE TITLE
UI Timeline Standard KeyframeSetting Alpha 0 ?

### ISSUE THREAD

**Issue by CeeYaa** [KairosResearchLab/Kairos#251]
it took me a while to understand that my Keyframes only seen via GetTrackValue (Kairos.CompositionSampler.Utils) when the Alpha in KeyframeSetting is not 0 - I understand the nice feature but when creating a Keyframe it would make more sense (for me) when Alpha is Standard 1

for every created Keyframe I have to reset the KeyframeSetting Alpha
Now only when I want to delete a Keyframe I set it to Zero but this feels wrong

**Comment by natan-sinigaglia** [comment]
confirmed, i just spotted this today.
i fixed. new keyframes have alpha 1.

Still keyframe's alpha needs to be properly visualized. I'll see what I can do
