### ISSUE TITLE
UI - KairosEditorBugs

### ISSUE THREAD

**Issue by CeeYaa** [KairosResearchLab/Kairos#256]
MainTool - it works and nothing got broken but less F9 usage, will increase the trust

MouseInteraction gone, 
want to move Keyframe suddenly AddKeyframe, 
felt more instable as more LIVE and/or LAYERS are involved, 
very instable or uncontrollable with Tabs, 
switching Views through many Timelines or Launchers getting also fast very instable or uncontrollable
suddenly heavy FrameDrops and manyTicks on Node KairosEditor

**Comment by natan-sinigaglia** [comment]
all of this is most likely fixed with the upcoming release (major UI window application rework)
