### ISSUE TITLE
Selecting and editing multiple keyframes

### ISSUE THREAD

**Issue by HydeNaut** [KairosResearchLab/Kairos#281]
Hi, I like to have a way to select and move/stretch keyframes over time. Something like this: 
![0f2a8c4107487ef02d72aa9c5551e81c1419b79f](https://github.com/KairosResearchLab/Kairos/assets/67781825/cc0ff09d-581e-4b2e-8c36-dca7c7c73623)
I can't say I know exactly what manner the interaction could be triggered (maybe with modifier keys, After-effects style) but it would help  lot if we want to record and edit small performances.
Thanks ,
H

**Comment by chkworks** [comment]
This is fixed, no?

**Comment by YanYas** [comment]
I'll call it done. I'll make a separate issue for stretching. Thanks for the reminder!
